@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor CustomerManager as Actor
participant DisplayCandidateDataUI as UI <<presentation>>
participant GetCandidateController as Controller <<application>>
database CandidateRepository as Repository <<repository>>
participant Candidate as Domain <<domain>>
participant CandidateDTO as DTO <<DTO>>

Actor --> UI: Display candidate data
activate UI
    UI --> Actor: Ask Candidate Email
    Actor --> UI: Candidate Email

    UI -> Controller: getCandidateData(Email)

    activate Controller
        Controller -> Repository: getCandidateByID(Email)

        activate Repository
            Repository -> Controller: candidate
        deactivate Repository


            Controller -> Domain: toDTO()

            Domain -> DTO: toDto()
            activate DTO
            DTO -> Controller: CandidateDTO
            deactivate DTO







        Controller -> UI: candidateDTO
    deactivate Controller


    UI --> Actor: Show candidate data

deactivate UI







deactivate UI
@enduml