@startuml
'http://plantuml.com/skinparam.html
'skinparam handwritten true
'skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor CustomerManager as Actor
participant EditJobOpeningUI as UI <<presentation>>
participant EditJobOpeningController as Controller <<application>>
participant JobOpeningSvc as Service <<application>>
participant JobOpeningDTO as DTO<<domain>>
participant JobOpening as Domain <<domain>>
database JobOpeningRepository as Repository <<repository>>
participant GetRequirementsController as ReqController <<application>>
participant GetInterviewModelController as IMController <<application>>
database InterviewModelRepository as IMRepository <<repository>>
database JobRequirementsRepository as JRRepository <<repository>>


Actor --> UI: edit job opening
activate UI

    UI --> Actor: ask to list all jobOpenings | get by job reference
    Actor --> UI
    note left of UI: if list view, get job opening\n by jobReference anyway
    UI -> Controller: get JobOpening list | search by jobReference
    activate Controller
        Controller -> Service: get JobOpening List | get JobOpening by jobReference
        activate Service
        Service -> Repository
            activate Repository
                Repository -> Domain
            deactivate Repository
            Domain-> DTO
            DTO -> Service
            Service -> Controller
        deactivate Service
        Controller->UI : list of JobOpeningDTOs | JobOpeningDTO
        deactivate Controller
    UI-->Actor: show JobOpeningDTO
    deactivate CustomerController
    UI --> Actor: Ask what to edit
    Actor --> UI: Description, VacancyNumber, Address, \nMode, ContractType, Title
    Actor --> UI: Set Recruitment Process
    UI -> Controller: RegisterJobOpening(JobReference, Company, \nDescription, Address, Mode, ContractType, \nVacancyNumber, Title, RecruitmentProcess)
    activate Controller
        Controller -> Builder : create
        note right of Builder: JobOpeningBuilder used to create a JobOpening entity in a valid state
        Controller -> Builder:setJobReference(acronym)
        note right of Controller: Set the rest of the information
        Controller -> Builder:registerJobOpening()
        activate Builder
            Builder -> Domain: registerJobOpening(JobReference, Company, \nDescription, Address, Mode, ContractType, \nVacancyNumber, Title, RecruitmentProcess)
            Domain->Builder: JobOpening
            Builder -> Controller:JobOpening
        deactivate Builder
        Controller -> Factory
        activate Factory
            Factory -> Repository : create
            Factory -> Controller : JobOpening
        deactivate Factory
        Controller -> Repository : save(JobOpening)
        Controller -> UI : JobOpening
    deactivate Controller
    UI-->Actor: displayJobOpeningInfo
deactivate UI
@enduml