@startuml
skinparam handwritten true
skinparam monochrome true
skinparam shadowing false

actor CustomerManager as Actor
participant ListJobOpeningsUI as UI <<presentation>>
participant ListJobOpeningsController as Controller <<application>>
participant JobOpeningRepository as Repository
participant JobOpeningDTOMapper as Mapper
participant JobOpeningDTO as DTO

Actor --> UI: Display candidate data
activate UI
    UI -> Controller: getAllJobOpenings()
    activate Controller
        Controller -> Repository: getAllJobOpenings()
        Repository -> Controller: list of job openings
        Controller -> Mapper : toDTO(jobOpenings)

        activate Mapper
        loop for each JobOpening in JobOpenings
            Mapper -> DTO : create()
        end
        Mapper -> Controller: JobOpeningsDTOList
        deactivate Mapper

        Controller -> UI: JobOpeningsDTOList
    deactivate Controller

    UI --> Actor: show all job openings

    Actor --> UI: Filter Job Openings
    note right of UI: Job openings can be filtered by date or customer
    UI -> Controller: filterBy(Customer|Date)
    activate Controller
        Controller -> Repository: filterBy(Customer|Date)
        Repository -> Controller: filtered job openings list

        Controller -> Mapper : toDTO(jobOpenings)
        activate Mapper
                loop for each JobOpening in JobOpenings
                    Mapper -> DTO : create()
                end
                Mapper -> Controller: JobOpeningsDTOList
                deactivate Mapper
        Controller -> UI: filtered job openings list
    deactivate Controller
    UI --> Actor: show filtered list
deactivate UI
@enduml
