@startuml
title US 2002 :: As Operator, I want to register an application of a candidate for a job opening and import all files received.
actor Operator
participant RegisterJobApplicationUI
participant RegisterJobApplicationController
participant JobOpeningRepository
participant JobApplication
participant JobApplicationRepository


Operator->RegisterJobApplicationUI: asks to create an JobApplication
activate RegisterJobApplicationUI
RegisterJobApplicationUI->RegisterJobApplicationController: List job openings

activate RegisterJobApplicationController
RegisterJobApplicationController->JobOpeningRepository: List job openings
activate JobOpeningRepository
JobOpeningRepository->RegisterJobApplicationController: Returns a list of job openings
deactivate JobOpeningRepository

RegisterJobApplicationController->RegisterJobApplicationUI: Returns a list of job openings
deactivate RegisterJobApplicationController
RegisterJobApplicationUI->Operator: Displays the list of job openings \n and asks to select one
deactivate RegisterJobApplicationUI

Operator->RegisterJobApplicationUI: Selects a job opening
activate RegisterJobApplicationUI
RegisterJobApplicationUI->Operator: Asks for application data and files
deactivate RegisterJobApplicationUI

Operator->RegisterJobApplicationUI: Submits data
activate RegisterJobApplicationUI
RegisterJobApplicationUI->RegisterJobApplicationController: registerApplication()
activate RegisterJobApplicationController

RegisterJobApplicationController->JobApplication: create()
RegisterJobApplicationController->JobApplicationRepository: save()
activate JobApplicationRepository

JobApplicationRepository->RegisterJobApplicationController: returns created application
deactivate JobApplicationRepository
RegisterJobApplicationController->RegisterJobApplicationUI: returns success
deactivate RegisterJobApplicationController

RegisterJobApplicationUI->Operator: Displays success message
deactivate RegisterJobApplicationUI

@enduml