@startuml
title US 2002 :: As Operator, I want to register an application of a candidate for a job opening and import all files received.
actor Operator
participant RegisterApplicationUI
participant RegisterApplicationController
participant JobOpeningRepository
participant Application
participant ApplicationRepository


Operator->RegisterApplicationUI: asks to create an Application
activate RegisterApplicationUI
RegisterApplicationUI->RegisterApplicationController: List job openings

activate RegisterApplicationController
RegisterApplicationController->JobOpeningRepository: List job openings
activate JobOpeningRepository
JobOpeningRepository->RegisterApplicationController: Returns a list of job openings
deactivate JobOpeningRepository

RegisterApplicationController->RegisterApplicationUI: Returns a list of job openings
deactivate RegisterApplicationController
RegisterApplicationUI->Operator: Displays the list of job openings \n and asks to select one
deactivate RegisterApplicationUI

Operator->RegisterApplicationUI: Selects a job opening
activate RegisterApplicationUI
RegisterApplicationUI->Operator: Asks for application data and files
deactivate RegisterApplicationUI

Operator->RegisterApplicationUI: Submits data
activate RegisterApplicationUI
RegisterApplicationUI->RegisterApplicationController: registerApplication()
activate RegisterApplicationController

RegisterApplicationController->Application: create()
RegisterApplicationController->ApplicationRepository: save()
activate ApplicationRepository

ApplicationRepository->RegisterApplicationController: returns created application
deactivate ApplicationRepository
RegisterApplicationController->RegisterApplicationUI: returns success
deactivate RegisterApplicationController

RegisterApplicationUI->Operator: Displays success message
deactivate RegisterApplicationUI

@enduml