@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor CustomerManager as Actor
participant AddCustomerUI as UI <<presentation>>
participant AddCustomerController as Controller <<application>>
participant "user:SystemUser" as Domain <<domain>>
participant "Customer" as CustomerDomain <<domain>>
participant BasePasswordPolicy as PassService


database UserRepository as UserRepository <<repository>>
database CustomerRepository as CustomerRepository <<repository>>

Actor --> UI: Add Customer
activate UI
    UI -> Controller: create
    UI --> Actor: Ask user information
    Actor --> UI: Customer Name, E-Mail


    UI -> Controller: addCustomer(name, email)
    activate Controller


        note right of Controller: Role = Customer

        Controller -> Domain: registerUser()
            activate Domain
                Domain-> PassService: generatePasssword()
                activate PassService
                    PassService -> Domain: validPassword
                deactivate PassService
            Domain -> Controller: SystemUser
            deactivate Domain

        Controller -> UserRepository: addUser()

        Controller -> CustomerDomain: new Customer()
        activate CustomerDomain
        CustomerDomain -> Controller: "Customer"
        deactivate CustomerDomain

        Controller -> CustomerRepository: save()




        Controller->UI: customer
    deactivate Controller

        UI-->Actor: displayUserInfo
deactivate UI
@enduml