@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten false
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor CustomerManager as Actor
participant RegisterJobOpeningUI as UI <<presentation>>
participant RecruitmentProcessController as Controller <<application>>
'participant PhaseBuilder as Builder <<builder>>



participant Phase as Domain <<domain>>
participant PersistenceContext as Persistence <<persistence>>
participant PhaseFactory as Factory <<factory>>
database PhaseRepository as Repository <<repository>>

Actor --> UI: Add Recruitment Process Phase
loop 4-5 Phases
activate UI
'    UI -> Controller: create
'    UI --> Actor: Ask user if he wants to add Interview phase
'    Actor --> UI: Yes/No



    UI -> Controller: create()
    activate Controller
'        note right of Builder:SystemUserBuilder é usado para criar uma entidade do tipo User num estado válido
'        Controller -> Builder: create
'        Controller -> Builder:setEmail(username)
'
'        note right of Controller: Set the rest of the information

        'Controller -> Builder:setPassword(password)
        'Controller -> Builder:setFirstName(firstName)
        'Controller -> Builder:setLastName(lastName)
        'Controller -> Builder:setEmail(email)
        'Controller -> Builder:setRoles(roles)

        Controller -> Factory:createPhase()
        activate Factory
            Factory -> Controller: ask period
            Controller -> UI: ask period
            UI-> Actor: ask period
            Actor -> UI : period
            UI->Controller : period

            Factory -> Domain : createPhase(Period)
            activate Domain
            note right of Domain: Types of phases:\n Application, Screening, Interview,\n Analysis, Result
            Domain -> Factory : Phase
            deactivate Domain
            Factory -> Controller : Phase
        deactivate Factory

        Controller -> Persistence: repositories()
        activate Persistence
            note right of Persistence: pode criar repositório em memória ou JPA
            Persistence -> Factory: create
            Persistence -> Controller: factory
        deactivate Persistence

        Controller -> Factory: users()
        activate Factory
            Factory -> Repository: create
            Factory -> Controller: userRepository
        deactivate Factory

        Controller->Repository:save(user)
        Controller->UI: Phase
    deactivate Controller
end
        UI-->Actor: displayUserInfo
deactivate UI
@enduml