# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven # --> Name of the workflow

on: # --> Events that will trigger the gitHub actions
  push: # --> Event
    branches:
      - main


jobs:  # --> Workflow that will be executed whenever the events are triggered
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # --> Action to be executed

    - name: Set up JDK 21 # Name given to the action
      uses: actions/setup-java@v4 # --> Action to be executed
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # To be confirmed .....
    - name: Build with Maven # Name given to the action
      run: mvn -B package --file pom.xml # --> Command to be run